// ============================================================
// Mock Data Layer — swap these functions for Prisma DB calls
// ============================================================
import { User, Project, Task, DailyLog, Notification, DashboardStats, AnalyticsData } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1', name: 'Sarah Chen', email: 'sarah@boss.dev', avatar: 'SC',
    role: 'PROJECT_MANAGER', department: 'Engineering', designation: 'Senior PM',
    skills: ['Agile', 'Scrum', 'Jira', 'Risk Management'], joinedAt: '2022-03-15',
    isActive: true, utilization: 87, billableRate: 150,
  },
  {
    id: 'u2', name: 'Marcus Rodriguez', email: 'marcus@boss.dev', avatar: 'MR',
    role: 'EMPLOYEE', department: 'Engineering', designation: 'Senior Developer',
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL'], joinedAt: '2021-08-01',
    isActive: true, utilization: 92, billableRate: 130,
  },
  {
    id: 'u3', name: 'Priya Sharma', email: 'priya@boss.dev', avatar: 'PS',
    role: 'TEAM_LEAD', department: 'Design', designation: 'Lead Designer',
    skills: ['Figma', 'UI/UX', 'Prototyping', 'Design Systems'], joinedAt: '2022-01-10',
    isActive: true, utilization: 78, billableRate: 120,
  },
  {
    id: 'u4', name: 'James Okonkwo', email: 'james@boss.dev', avatar: 'JO',
    role: 'EMPLOYEE', department: 'Engineering', designation: 'Backend Developer',
    skills: ['Python', 'FastAPI', 'Docker', 'Kubernetes'], joinedAt: '2023-02-20',
    isActive: true, utilization: 95, billableRate: 125,
  },
  {
    id: 'u5', name: 'Aisha Thompson', email: 'aisha@boss.dev', avatar: 'AT',
    role: 'EMPLOYEE', department: 'QA', designation: 'QA Engineer',
    skills: ['Selenium', 'Jest', 'Cypress', 'Test Planning'], joinedAt: '2022-11-05',
    isActive: true, utilization: 72, billableRate: 110,
  },
  {
    id: 'u6', name: 'Liam Walsh', email: 'liam@boss.dev', avatar: 'LW',
    role: 'ADMIN', department: 'Management', designation: 'CTO',
    skills: ['Architecture', 'Leadership', 'Strategy'], joinedAt: '2020-06-01',
    isActive: true, utilization: 65, billableRate: 200,
  },
  {
    id: 'u7', name: 'Elena Vasquez', email: 'elena@boss.dev', avatar: 'EV',
    role: 'EMPLOYEE', department: 'Engineering', designation: 'Frontend Developer',
    skills: ['React', 'Vue.js', 'CSS', 'Animation'], joinedAt: '2023-05-15',
    isActive: true, utilization: 88, billableRate: 115,
  },
  {
    id: 'u8', name: 'David Kim', email: 'david@boss.dev', avatar: 'DK',
    role: 'EMPLOYEE', department: 'DevOps', designation: 'DevOps Engineer',
    skills: ['AWS', 'Terraform', 'CI/CD', 'Monitoring'], joinedAt: '2022-07-22',
    isActive: true, utilization: 81, billableRate: 135,
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'E-Commerce Platform Rebuild',
    description: 'Complete overhaul of legacy e-commerce system with modern React/Node stack, improved performance, and new feature set.',
    client: 'RetailCorp Inc.',
    status: 'ACTIVE',
    priority: 'HIGH',
    startDate: '2026-02-01',
    endDate: '2026-07-31',
    budget: 280000,
    spentBudget: 142000,
    completionPercent: 54,
    healthScore: 72,
    riskLevel: 'MEDIUM',
    managerId: 'u1',
    manager: MOCK_USERS[0],
    members: [
      { userId: 'u2', user: MOCK_USERS[1], projectId: 'p1', role: 'LEAD', allocation: 100, joinedAt: '2026-02-01' },
      { userId: 'u3', user: MOCK_USERS[2], projectId: 'p1', role: 'MEMBER', allocation: 60, joinedAt: '2026-02-01' },
      { userId: 'u4', user: MOCK_USERS[3], projectId: 'p1', role: 'MEMBER', allocation: 80, joinedAt: '2026-02-01' },
      { userId: 'u5', user: MOCK_USERS[4], projectId: 'p1', role: 'MEMBER', allocation: 50, joinedAt: '2026-03-01' },
    ],
    tasks: [],
    milestones: [
      { id: 'm1', projectId: 'p1', title: 'Architecture Design', description: 'System architecture finalized', dueDate: '2026-02-28', completedAt: '2026-02-25', status: 'COMPLETED' },
      { id: 'm2', projectId: 'p1', title: 'Core APIs Live', description: 'All backend APIs deployed', dueDate: '2026-04-30', status: 'PENDING' },
      { id: 'm3', projectId: 'p1', title: 'Beta Release', description: 'Beta version available to client', dueDate: '2026-06-30', status: 'PENDING' },
    ],
    tags: ['e-commerce', 'react', 'node', 'priority'],
    createdAt: '2026-01-15',
    updatedAt: '2026-05-05',
  },
  {
    id: 'p2',
    name: 'AI Analytics Dashboard',
    description: 'Machine learning powered analytics platform with real-time insights, predictive modeling, and executive reporting.',
    client: 'DataDriven Labs',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    startDate: '2026-03-15',
    endDate: '2026-08-15',
    budget: 195000,
    spentBudget: 67000,
    completionPercent: 31,
    healthScore: 88,
    riskLevel: 'LOW',
    managerId: 'u1',
    manager: MOCK_USERS[0],
    members: [
      { userId: 'u2', user: MOCK_USERS[1], projectId: 'p2', role: 'MEMBER', allocation: 40, joinedAt: '2026-03-15' },
      { userId: 'u6', user: MOCK_USERS[5], projectId: 'p2', role: 'LEAD', allocation: 30, joinedAt: '2026-03-15' },
      { userId: 'u7', user: MOCK_USERS[6], projectId: 'p2', role: 'MEMBER', allocation: 100, joinedAt: '2026-03-15' },
    ],
    tasks: [],
    milestones: [
      { id: 'm4', projectId: 'p2', title: 'Data Pipeline Setup', description: 'ETL pipelines operational', dueDate: '2026-04-30', completedAt: '2026-04-28', status: 'COMPLETED' },
      { id: 'm5', projectId: 'p2', title: 'ML Model Integration', description: 'Models integrated and validated', dueDate: '2026-06-30', status: 'PENDING' },
    ],
    tags: ['ai', 'ml', 'analytics', 'dashboard'],
    createdAt: '2026-03-01',
    updatedAt: '2026-05-06',
  },
  {
    id: 'p3',
    name: 'Mobile App v2.0',
    description: 'React Native mobile app redesign with offline support, push notifications, and new onboarding flow.',
    client: 'UrbanMobility Co.',
    status: 'AT_RISK',
    priority: 'HIGH',
    startDate: '2026-01-10',
    endDate: '2026-05-31',
    budget: 120000,
    spentBudget: 98000,
    completionPercent: 78,
    healthScore: 45,
    riskLevel: 'HIGH',
    managerId: 'u1',
    manager: MOCK_USERS[0],
    members: [
      { userId: 'u3', user: MOCK_USERS[2], projectId: 'p3', role: 'LEAD', allocation: 40, joinedAt: '2026-01-10' },
      { userId: 'u7', user: MOCK_USERS[6], projectId: 'p3', role: 'MEMBER', allocation: 80, joinedAt: '2026-01-10' },
      { userId: 'u8', user: MOCK_USERS[7], projectId: 'p3', role: 'MEMBER', allocation: 40, joinedAt: '2026-01-10' },
    ],
    tasks: [],
    milestones: [
      { id: 'm6', projectId: 'p3', title: 'App Store Submission', description: 'App submitted to both stores', dueDate: '2026-05-20', status: 'PENDING' },
    ],
    tags: ['mobile', 'react-native', 'redesign'],
    createdAt: '2025-12-20',
    updatedAt: '2026-05-04',
  },
  {
    id: 'p4',
    name: 'Cloud Migration Initiative',
    description: 'Migrate on-premise infrastructure to AWS with zero downtime, IaC implementation, and cost optimization.',
    client: 'Internal',
    status: 'PLANNING',
    priority: 'MEDIUM',
    startDate: '2026-06-01',
    endDate: '2026-10-31',
    budget: 85000,
    spentBudget: 5000,
    completionPercent: 8,
    healthScore: 95,
    riskLevel: 'MEDIUM',
    managerId: 'u1',
    manager: MOCK_USERS[0],
    members: [
      { userId: 'u4', user: MOCK_USERS[3], projectId: 'p4', role: 'LEAD', allocation: 20, joinedAt: '2026-05-01' },
      { userId: 'u8', user: MOCK_USERS[7], projectId: 'p4', role: 'MEMBER', allocation: 60, joinedAt: '2026-05-01' },
    ],
    tasks: [],
    milestones: [],
    tags: ['cloud', 'aws', 'devops', 'infrastructure'],
    createdAt: '2026-04-20',
    updatedAt: '2026-05-01',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 't1', title: 'Implement Product Listing API', description: 'Build RESTful endpoints for product catalog with filtering, sorting, pagination, and search capabilities.', projectId: 'p1',
    assigneeId: 'u4', assignee: MOCK_USERS[3], reporterId: 'u1', reporter: MOCK_USERS[0],
    status: 'IN_PROGRESS', priority: 'HIGH', startDate: '2026-04-28', dueDate: '2026-05-10',
    estimatedHours: 32, actualHours: 24, progressPercent: 75, labels: ['backend', 'api'],
    subtasks: [
      { id: 'st1', title: 'Design API schema', completed: true },
      { id: 'st2', title: 'Write endpoint handlers', completed: true },
      { id: 'st3', title: 'Add filtering & pagination', completed: false },
      { id: 'st4', title: 'Write unit tests', completed: false },
    ],
    comments: [], attachments: [], dependencies: [], watchers: ['u1', 'u2'],
    createdAt: '2026-04-25', updatedAt: '2026-05-05',
  },
  {
    id: 't2', title: 'Shopping Cart & Checkout UI', description: 'React components for cart management, checkout flow, address selection, and order summary.',
    projectId: 'p1', assigneeId: 'u7', assignee: MOCK_USERS[6], reporterId: 'u2', reporter: MOCK_USERS[1],
    status: 'IN_PROGRESS', priority: 'HIGH', startDate: '2026-05-01', dueDate: '2026-05-15',
    estimatedHours: 40, actualHours: 18, progressPercent: 45, labels: ['frontend', 'ux'],
    subtasks: [
      { id: 'st5', title: 'Cart component', completed: true },
      { id: 'st6', title: 'Checkout flow', completed: false },
      { id: 'st7', title: 'Payment integration UI', completed: false },
    ],
    comments: [], attachments: [], dependencies: ['t1'], watchers: ['u1', 'u3'],
    createdAt: '2026-04-28', updatedAt: '2026-05-05',
  },
  {
    id: 't3', title: 'Design System — Component Library', description: 'Establish token-based design system with 40+ reusable components, dark mode, and Storybook documentation.',
    projectId: 'p1', assigneeId: 'u3', assignee: MOCK_USERS[2], reporterId: 'u1', reporter: MOCK_USERS[0],
    status: 'COMPLETED', priority: 'HIGH', startDate: '2026-02-15', dueDate: '2026-03-30',
    estimatedHours: 80, actualHours: 88, progressPercent: 100, labels: ['design', 'frontend'],
    subtasks: [], comments: [], attachments: [], dependencies: [], watchers: ['u1', 'u7'],
    createdAt: '2026-02-10', updatedAt: '2026-03-30',
  },
  {
    id: 't4', title: 'Payment Gateway Integration', description: 'Stripe integration with webhook handling, refund flows, and PCI-compliant data handling.',
    projectId: 'p1', assigneeId: 'u4', assignee: MOCK_USERS[3], reporterId: 'u1', reporter: MOCK_USERS[0],
    status: 'BLOCKED', priority: 'CRITICAL', startDate: '2026-05-01', dueDate: '2026-05-20',
    estimatedHours: 48, actualHours: 8, progressPercent: 15, labels: ['backend', 'payments'],
    subtasks: [], comments: [], attachments: [], dependencies: ['t1'], watchers: ['u1', 'u2', 'u4'],
    createdAt: '2026-04-28', updatedAt: '2026-05-04',
  },
  {
    id: 't5', title: 'Real-time Dashboard Widgets', description: 'Build responsive chart components using Recharts for the AI analytics dashboard.',
    projectId: 'p2', assigneeId: 'u7', assignee: MOCK_USERS[6], reporterId: 'u6', reporter: MOCK_USERS[5],
    status: 'IN_PROGRESS', priority: 'HIGH', startDate: '2026-05-01', dueDate: '2026-05-18',
    estimatedHours: 36, actualHours: 12, progressPercent: 35, labels: ['frontend', 'charts'],
    subtasks: [], comments: [], attachments: [], dependencies: [], watchers: ['u1', 'u6'],
    createdAt: '2026-04-28', updatedAt: '2026-05-05',
  },
  {
    id: 't6', title: 'E2E Test Suite — Checkout Flow', description: 'Cypress end-to-end tests covering complete purchase flow from product discovery to order confirmation.',
    projectId: 'p1', assigneeId: 'u5', assignee: MOCK_USERS[4], reporterId: 'u2', reporter: MOCK_USERS[1],
    status: 'NOT_STARTED', priority: 'MEDIUM', startDate: '2026-05-16', dueDate: '2026-05-28',
    estimatedHours: 24, actualHours: 0, progressPercent: 0, labels: ['testing', 'qa'],
    subtasks: [], comments: [], attachments: [], dependencies: ['t2'], watchers: ['u1'],
    createdAt: '2026-05-01', updatedAt: '2026-05-01',
  },
];

export const MOCK_DAILY_LOGS: DailyLog[] = [
  {
    id: 'dl1', userId: 'u4', user: MOCK_USERS[3], projectId: 'p1', taskId: 't1',
    date: '2026-05-06', status: 'IN_PROGRESS',
    summary: 'Implemented filtering logic for product API. Added price range, category, and availability filters. Pagination working correctly.',
    hoursWorked: 7.5,
    deliverablesCompleted: ['Price filter endpoint', 'Category filter endpoint', 'Pagination middleware'],
    blockers: 'Waiting for Stripe API keys to test payment flow on t4. Raised with Sarah.',
    tomorrowPlan: 'Complete sorting logic, add full-text search, begin unit tests.',
    progressPercent: 75,
    attachments: [],
    createdAt: '2026-05-06T17:30:00Z',
  },
  {
    id: 'dl2', userId: 'u7', user: MOCK_USERS[6], projectId: 'p1', taskId: 't2',
    date: '2026-05-06', status: 'IN_PROGRESS',
    summary: 'Built cart sidebar component with quantity controls and remove functionality. Started checkout step 1 (address form).',
    hoursWorked: 8,
    deliverablesCompleted: ['CartSidebar component', 'Quantity controller', 'Address form UI'],
    blockers: 'None',
    tomorrowPlan: 'Complete checkout steps 2-3, integrate with cart API once t1 is done.',
    progressPercent: 45,
    attachments: [],
    createdAt: '2026-05-06T18:00:00Z',
  },
  {
    id: 'dl3', userId: 'u3', user: MOCK_USERS[2], projectId: 'p2', taskId: 't5',
    date: '2026-05-05', status: 'IN_PROGRESS',
    summary: 'Reviewed Figma designs for mobile app landing screen. Provided detailed feedback on typography scale and spacing system.',
    hoursWorked: 5.5,
    deliverablesCompleted: ['Design review doc', '12 Figma comment annotations'],
    blockers: 'Need client approval on revised color palette before proceeding.',
    tomorrowPlan: 'Iterate on onboarding screens based on PM feedback.',
    progressPercent: 60,
    attachments: [],
    createdAt: '2026-05-05T17:00:00Z',
  },
  {
    id: 'dl4', userId: 'u2', user: MOCK_USERS[1], projectId: 'p1', taskId: 't2',
    date: '2026-05-06', status: 'IN_PROGRESS',
    summary: 'Code reviewed 3 PRs. Pair programmed with Elena on cart state management. Updated architecture docs.',
    hoursWorked: 7,
    deliverablesCompleted: ['3 PRs reviewed', 'Architecture docs updated', 'Cart state refactor'],
    blockers: 'None',
    tomorrowPlan: 'Continue code reviews, begin performance profiling of product list.',
    progressPercent: 45,
    attachments: [],
    createdAt: '2026-05-06T17:45:00Z',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'n1', userId: 'u1', type: 'BLOCKER_ESCALATION', title: 'Blocker on Payment Integration', message: 'Task "Payment Gateway Integration" has been blocked for 3 days. James is waiting for Stripe API keys.', link: '/tasks/t4', isRead: false, createdAt: '2026-05-06T09:00:00Z' },
  { id: 'n2', userId: 'u1', type: 'TASK_OVERDUE', title: 'Task Approaching Deadline', message: '"Shopping Cart & Checkout UI" is due in 9 days with 45% completion.', link: '/tasks/t2', isRead: false, createdAt: '2026-05-06T08:00:00Z' },
  { id: 'n3', userId: 'u2', type: 'TASK_ASSIGNED', title: 'New Task Assigned', message: 'You have been assigned "Performance Profiling — Product List"', link: '/tasks/t7', isRead: true, createdAt: '2026-05-05T14:00:00Z' },
  { id: 'n4', userId: 'u4', type: 'DAILY_LOG_REMINDER', title: 'Daily Log Reminder', message: 'Don\'t forget to submit your daily work log for today.', link: '/daily-log', isRead: false, createdAt: '2026-05-06T17:00:00Z' },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalProjects: 4,
  activeProjects: 2,
  delayedProjects: 1,
  totalResources: 8,
  activeResources: 8,
  avgUtilization: 82.3,
  tasksCompletedToday: 3,
  upcomingDeadlines: 4,
  overdueTasks: 1,
  productivityScore: 78,
  burnRate: 94500,
};

export const MOCK_ANALYTICS: AnalyticsData = {
  projectHealth: [
    { name: 'E-Commerce Rebuild', score: 72, status: 'ACTIVE' },
    { name: 'AI Analytics', score: 88, status: 'ACTIVE' },
    { name: 'Mobile App v2', score: 45, status: 'AT_RISK' },
    { name: 'Cloud Migration', score: 95, status: 'PLANNING' },
  ],
  teamProductivity: [
    { date: 'Apr 28', tasksCompleted: 8, hoursLogged: 58 },
    { date: 'Apr 29', tasksCompleted: 12, hoursLogged: 62 },
    { date: 'Apr 30', tasksCompleted: 7, hoursLogged: 55 },
    { date: 'May 1', tasksCompleted: 15, hoursLogged: 64 },
    { date: 'May 2', tasksCompleted: 11, hoursLogged: 60 },
    { date: 'May 5', tasksCompleted: 9, hoursLogged: 57 },
    { date: 'May 6', tasksCompleted: 13, hoursLogged: 61 },
  ],
  resourceUtilization: MOCK_USERS.map(u => ({
    userId: u.id, user: u,
    weeklyHours: Math.round(u.utilization * 0.4),
    utilizationPercent: u.utilization,
    billableHours: Math.round(u.utilization * 0.35),
    nonBillableHours: Math.round(u.utilization * 0.05),
    projectBreakdown: [],
    trend: u.utilization > 85 ? 'UP' : u.utilization < 70 ? 'DOWN' : 'STABLE' as 'UP' | 'DOWN' | 'STABLE',
  })),
  burndownData: [
    { date: 'May 1', remaining: 180, ideal: 180 },
    { date: 'May 2', remaining: 165, ideal: 156 },
    { date: 'May 3', remaining: 148, ideal: 132 },
    { date: 'May 4', remaining: 135, ideal: 108 },
    { date: 'May 5', remaining: 122, ideal: 84 },
    { date: 'May 6', remaining: 110, ideal: 60 },
  ],
  velocityData: [
    { sprint: 'Sprint 1', committed: 32, completed: 28 },
    { sprint: 'Sprint 2', committed: 36, completed: 34 },
    { sprint: 'Sprint 3', committed: 40, completed: 38 },
    { sprint: 'Sprint 4', committed: 42, completed: 35 },
    { sprint: 'Sprint 5', committed: 38, completed: 39 },
  ],
  statusDistribution: [
    { status: 'COMPLETED', count: 18 },
    { status: 'IN_PROGRESS', count: 12 },
    { status: 'NOT_STARTED', count: 8 },
    { status: 'BLOCKED', count: 2 },
    { status: 'IN_REVIEW', count: 5 },
  ],
  delayedTasks: [MOCK_TASKS[3]],
  topPerformers: [
    { user: MOCK_USERS[3], score: 94, tasksCompleted: 12 },
    { user: MOCK_USERS[1], score: 91, tasksCompleted: 10 },
    { user: MOCK_USERS[6], score: 87, tasksCompleted: 9 },
    { user: MOCK_USERS[4], score: 82, tasksCompleted: 8 },
  ],
};
